# Generated by Django 5.1.2 on 2024-10-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('frist_name', models.CharField(max_length=55, verbose_name='Фамиля')),
                ('age', models.BigIntegerField(verbose_name='Дата рождения')),
                ('description', models.TextField(verbose_name='О себе')),
            ],
        ),
    ]
